# labels: "smile" 
labels: "age" 
dec_dist: "implicit" 
d_steps_per_iter: 1 
sample_every_epoch: 5 
latent_dim: 100 
enc_arch: "resnet" 
save_model_every: 50 
n_epochs: 200 
prior: "linscm" 
sup_prop: 1 
sup_coef: 5 
sup_type: "ce"